version: '3.9'

services:
  web:
    build: .
    command: gunicorn poligon_it.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    entrypoint: ["/app/entrypoint.sh"]
    environment:
    - RUN_MIGRATIONS=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/backend/media
    depends_on:
      - web



  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A backend.poligon_it worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web
      - redis
    working_dir: /app/backend

  celery-beat:
    build: .
    command: celery -A backend.poligon_it beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web
      - redis
    working_dir: /app/backend


  bot:
    build: .
    command: python backend/tg_bot/run_bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
