version: '3.8'

services:
  web:
    build: .
    working_dir: /app
    command: ["gunicorn", "poligon_it.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    working_dir: /app
    command: ["celery", "-A", "poligon_it.poligon_it", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build: .
    working_dir: /app
    command: ["celery", "-A", "poligon_it.poligon_it", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
