# Generated by Django 5.1.7 on 2025-04-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complectation',
            field=models.TextField(blank=True, default=dict, verbose_name='Комлектация товара'),
        ),
    ]
