# Generated by Django 5.1.7 on 2025-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_complectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complectation',
            field=models.JSONField(blank=True, default=dict, verbose_name='Комлектация товара'),
        ),
    ]
