# Generated by Django 5.1.7 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_complectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complectation',
            field=models.TextField(blank=True, verbose_name='Комлектация товара'),
        ),
    ]
