# Generated by Django 5.1.7 on 2025-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_complectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory_1',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
