# Generated by Django 5.1.7 on 2025-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subcategory_1_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('by_orderПод заказ', 'By Order')], default='in_stock', verbose_name='Доступность'),
        ),
    ]
