# Generated by Django 5.1.7 on 2025-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_tree',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_two',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('by_order', 'Под заказ')], default='in_stock', verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certificate_diller',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат 1'),
        ),
    ]
