# Generated by Django 5.1.7 on 2025-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_certificate_tree_product_certificate_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
    ]
