# Generated by Django 5.1.7 on 2025-08-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_image_2_alter_product_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='product/'),
        ),
    ]
